name: Reference Documentation
description: Report an issue related to API reference documentation.
title: "[reference]: <Please write a comprehensive title>"
labels: [reference]

body:
  - type: dropdown
    attributes:
      label: "Type of issue"
      description: "What type of reference documentation issue are you reporting?"
      options:
        - issue / bug
        - missing documentation
        - incorrect type signature
        - outdated/deprecated content
        - other
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Language"
      description: "What language is the reference documentation issue related to?"
      options:
        - Python
        - JavaScript
        - N/A
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Product"
      description: "Which product's reference docs is this issue related to?"
      options:
        - LangChain
        - LangGraph
        - LangSmith
        - Other
      default: 0
  - type: input
    attributes:
      label: "Link to reference page"
      description: "URL to the specific reference page with the issue (if applicable)"
  - type: textarea
    attributes:
      label: "Description"
      description: >
        Please describe your issue in detail.
        For missing documentation, specify the class/method/function that needs documentation.
        For incorrect signatures, provide the expected vs. actual signature.
        For bugs, include what you expected to see vs. what you actually see.
        [Read v1 announcement](https://github.com/langchain-ai/docs/issues/1007)
      placeholder: >
        !!! Before submitting, please review the v1 announcement (linked above) for the
        release notes and migration guides to see if your question or issue has been addressed.
    validations:
      required: true
