[project]
name = "langchain-reference-docs"
version = "0.1.0"
description = "LangChain API reference documentation"
requires-python = ">=3.13.0,<4.0.0"
readme = "README.md"
license = "MIT"
dependencies = [
    # Core reference build dependencies
    "mkdocs>=1.6.0,<2.0.0",
    "mkdocs-material[imaging]>=9.6.20,<10.0.0",
    "mkdocstrings>=0.24.0,<1.0.0",
    "mkdocs-minify-plugin>=0.8.0,<1.0.0",
    "mkdocs-git-committers-plugin-2>=1.2.0,<2.0.0",
    "mkdocs-git-authors-plugin>=0.10.0,<1.0.0",
    "markdown-callouts>=0.3.0,<1.0.0",
    "markdown-include>=0.8.1,<1.0.0",
    "mkdocs-exclude>=1.0.2,<2.0.0",
    "mkdocs-exclude-search>=0.6.5,<1.0.0",
    "mkdocs-include-markdown-plugin>=7.1.6,<8.0.0",
    # TODO: audit above dependencies
    # I copied them over because they were in LangGraph's
    # Not sure if each were used/apply to this project
    "griffe-warnings-deprecated>=1.1.0,<2.0.0",
    "griffe-inherited-docstrings>=1.1.2,<2.0.0",
    # Python
    "mkdocstrings-python>=1.7.0,<2.0.0",
    # Format / Lint
    "ruff>=0.13.0,<14.0.0",
    # Libraries
    #"langchain-cli",
    "langchain-core",
    "langchain",
    "langchain-classic",
    "langchain-tests",
    "langchain-text-splitters",
    "langchain-anthropic",
    "langchain-chroma",
    "langchain-deepseek",
    "langchain-exa",
    "langchain-fireworks",
    "langchain-groq",
    "langchain-huggingface",
    "langchain-mistralai",
    "langchain-nomic",
    "langchain-ollama",
    "langchain-openai",
    "langchain-perplexity",
    "langchain-prompty",
    "langchain-qdrant",
    "langchain-xai",
    #"langchain-experimental",
    "langchain-community",
    "langchain-mcp-adapters",
    "langchain-astradb",
    #"langchain-ai21",
    "langchain-aws",
    "langchain-azure-ai",
    #"langchain-azure-dynamic-sessions",
    "langchain-azure-storage",
    #"langchain-cerebras",
    #"langchain-cohere",
    #"langchain-db2",
    #"langchain-elasticsearch",
    "langchain-google-community",
    "langchain-google-genai",
    "langchain-google-vertexai",
    #"langchain-ibm",
    "langchain-milvus",
    "langchain-neo4j",
    #"langchain-nvidia-ai-endpoints",
    #"langchain-pinecone",
    #"langchain-postgres",
    #"langchain-redis",
    #"langchain-sema4",
    #"langchain-snowflake",
    #"langchain-sqlserver",
    #"langchain-together",
    #"langchain-unstructured",
    #"langchain-upstage",
    #"langchain-weaviate",
    "langchain-tavily",
    "langgraph",
    "langgraph-prebuilt",
    "langgraph-checkpoint",
    "langgraph-checkpoint-sqlite",
    "langgraph-checkpoint-postgres",
    "langgraph-sdk",
    #"langgraph-supervisor",
    #"langgraph-swarm",
    "langgraph-checkpoint-aws",
    "langsmith",
    "deepagents"
]


[tool.uv]
package = false
# Use copy mode instead of hardlink to avoid filesystem compatibility issues
# This is necessary for CI/CD environments like Vercel where cache and target
# directories may be on different filesystems
link-mode = "copy"
override-dependencies = [
    "pytest-codspeed>=3.1.0,<4.0.0",
]

[tool.uv.sources]
# Remote installs for prod

## LangChain monorepo packages (alphabetical)
### Top level
#langchain-cli = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/cli" }
langchain-core = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/core" }
langchain = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/langchain_v1" }
langchain-classic = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/langchain" }
langchain-tests = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/standard-tests" }
langchain-text-splitters = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/text-splitters" }

### Partners
langchain-anthropic = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/anthropic" }
langchain-chroma = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/chroma" }
langchain-deepseek = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/deepseek" }
langchain-exa = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/exa" }
langchain-fireworks = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/fireworks" }
langchain-groq = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/groq" }
langchain-huggingface = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/huggingface" }
langchain-mistralai = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/mistralai" }
langchain-nomic = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/nomic" }
langchain-ollama = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/ollama" }
langchain-openai = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/openai" }
langchain-perplexity = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/perplexity" }
langchain-prompty = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/prompty" }
langchain-qdrant = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/qdrant" }
langchain-xai = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/xai" }

## Experimental
#langchain-experimental = { git = "https://github.com/langchain-ai/langchain-experimental.git", subdirectory = "libs/experimental" }

## Community
langchain-community = { git = "https://github.com/langchain-ai/langchain-community.git", subdirectory = "libs/community" }

## MCP
langchain-mcp-adapters = { git = "https://github.com/langchain-ai/langchain-mcp-adapters.git" }

## Other langchain-ai org packages (alphabetical)
langchain-astradb = { git = "https://github.com/langchain-ai/langchain-datastax.git", subdirectory = "libs/astradb" }
langchain-ai21 = { git = "https://github.com/langchain-ai/langchain-ai21.git", subdirectory = "libs/ai21" }
langchain-aws = { git = "https://github.com/langchain-ai/langchain-aws.git", subdirectory = "libs/aws" }
langchain-azure-ai = { git = "https://github.com/langchain-ai/langchain-azure.git", subdirectory = "libs/azure-ai" }
langchain-azure-dynamic-sessions = { git = "https://github.com/langchain-ai/langchain-azure.git", subdirectory = "libs/azure-dynamic-sessions" }
langchain-azure-storage = { git = "https://github.com/langchain-ai/langchain-azure.git", subdirectory = "libs/azure-storage" }
langchain-cerebras = { git = "https://github.com/langchain-ai/langchain-cerebras.git", subdirectory = "libs/cerebras" }
langchain-cohere = { git = "https://github.com/langchain-ai/langchain-cohere.git", subdirectory = "libs/cohere" }
langchain-db2 = { git = "https://github.com/langchain-ai/langchain-ibm.git", subdirectory = "libs/langchain-db2" }
langchain-elasticsearch = { git = "https://github.com/langchain-ai/langchain-elastic.git", subdirectory = "libs/elasticsearch" }
langchain-google-community = { git = "https://github.com/langchain-ai/langchain-google.git", subdirectory = "libs/community" }
langchain-google-genai = { git = "https://github.com/langchain-ai/langchain-google.git", subdirectory = "libs/genai" }
langchain-google-vertexai = { git = "https://github.com/langchain-ai/langchain-google.git", subdirectory = "libs/vertexai" }
langchain-ibm = { git = "https://github.com/langchain-ai/langchain-ibm.git", subdirectory = "libs/ibm" }
langchain-milvus = { git = "https://github.com/langchain-ai/langchain-milvus.git", subdirectory = "libs/milvus" }
langchain-neo4j = { git = "https://github.com/langchain-ai/langchain-neo4j.git", subdirectory = "libs/neo4j" }
langchain-nvidia-ai-endpoints = { git = "https://github.com/langchain-ai/langchain-nvidia.git", subdirectory = "libs/ai-endpoints" }
langchain-pinecone = { git = "https://github.com/langchain-ai/langchain-pinecone.git", subdirectory = "libs/pinecone" }
langchain-postgres = { git = "https://github.com/langchain-ai/langchain-postgres.git" }
langchain-redis = { git = "https://github.com/langchain-ai/langchain-redis.git", subdirectory = "libs/redis" }
langchain-sema4 = { git = "https://github.com/langchain-ai/langchain-sema4.git", subdirectory = "libs/sema4" }
langchain-snowflake = { git = "https://github.com/langchain-ai/langchain-snowflake.git", subdirectory = "libs/snowflake" }
langchain-sqlserver = { git = "https://github.com/langchain-ai/langchain-azure.git", subdirectory = "libs/sqlserver" }
langchain-together = { git = "https://github.com/langchain-ai/langchain-together.git", subdirectory = "libs/together" }
langchain-unstructured = { git = "https://github.com/langchain-ai/langchain-unstructured.git", subdirectory = "libs/unstructured" }
langchain-upstage = { git = "https://github.com/langchain-ai/langchain-upstage.git", subdirectory = "libs/upstage" }
langchain-weaviate = { git = "https://github.com/langchain-ai/langchain-weaviate.git", subdirectory = "libs/weaviate", branch = "v1.0" }

## Non-langchain-ai org packages (alphabetical)
langchain-tavily = { git = "https://github.com/tavily-ai/langchain-tavily.git" }

## LangGraph monorepo packages (alphabetical)
langgraph = { git = "https://github.com/langchain-ai/langgraph", subdirectory = "libs/langgraph" }
langgraph-prebuilt = { git = "https://github.com/langchain-ai/langgraph", subdirectory = "libs/prebuilt" }
langgraph-checkpoint = { git = "https://github.com/langchain-ai/langgraph", subdirectory = "libs/checkpoint" }
langgraph-checkpoint-sqlite = { git = "https://github.com/langchain-ai/langgraph", subdirectory = "libs/checkpoint-sqlite" }
langgraph-checkpoint-postgres = { git = "https://github.com/langchain-ai/langgraph", subdirectory = "libs/checkpoint-postgres" }
langgraph-sdk = { git = "https://github.com/langchain-ai/langgraph", subdirectory = "libs/sdk-py" }

# External repos (alphabetical)
langgraph-supervisor = { git = "https://github.com/langchain-ai/langgraph-supervisor-py" }
langgraph-swarm = { git = "https://github.com/langchain-ai/langgraph-swarm-py" }
langgraph-checkpoint-aws = { git = "https://github.com/langchain-ai/langchain-aws.git", subdirectory = "libs/langgraph-checkpoint-aws" }

# LangSmith
langsmith = { git = "https://github.com/langchain-ai/langsmith-sdk.git", subdirectory = "python" }

# Deep Agents
deepagents = { git = "https://github.com/langchain-ai/deepagents.git" }
