# Documentation Build & Link Validation
#
# This reusable workflow builds documentation using Python/Make and validates
# all internal and external links using Mintlify's link checker.
#
# Usage:
#   jobs:
#     docs-validation:
#       uses: ./.github/workflows/check-links.yml
#       with:
#         python-version: "3.13"
#
# Requirements:
#   - A Makefile with a 'build' target in the repository root
#   - Python dependencies managed via uv with a 'test' group
#   - Generated documentation compatible with Mintlify link checker

name: Documentation Build & Link Validation

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        description: "Python version for building documentation (e.g., '3.13')"

env:
  UV_FROZEN: "true"
  UV_NO_SYNC: "true"

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: "Documentation Build & Link Check (Python ${{ inputs.python-version }})"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Python ${{ inputs.python-version }} with uv package manager
        uses: "./.github/actions/uv_setup"
        id: setup-python
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Python dependencies
        shell: bash
        run: uv sync --group test

      - name: Configure Node.js runtime
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install Mintlify CLI
        run: npm i -g mint@4.2.126

      - name: Validate documentation links
        run: make broken-links
